"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS1.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome1.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS2.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome2.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS3.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome3.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS4.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome4.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS5.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome5.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS6.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome6.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS7.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome7.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS8.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome8.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS9.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome9.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS10.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome10.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS11.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome11.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS12.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome12.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS13.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome13.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS14.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome14.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS15.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome15.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS16.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome16.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS17.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome17.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS18.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome18.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS19.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome19.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS20.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome20.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS21.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome21.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS22.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome22.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS23.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome23.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS24.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome24.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS25.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome25.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS26.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome26.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS27.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome27.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS28.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome28.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS29.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome29.csv" --discountrate 2 
 
"C:\Users\elrog\COBRA\cobra_console.exe" -d "C:\Users\elrog\COBRA\data\cobra.db" -b "C:\Users\elrog\COBRA\input files\new data\Emissions_2023_baseline_data.csv" -c "C:\Users\elrog\COBRA\input files\new data\EmissionsScenarios\EmissionsScenariosTest3_seed5\Emissions_ScenarioTONS30.csv" -p "C:\Users\elrog\COBRA\input files\new data\default_2023_population_data.csv" -i "C:\Users\elrog\COBRA\input files\new data\default_2023_incidence_data.csv" -v "C:\Users\elrog\COBRA\input files\new data\default_2023_valuation_data.csv" -o "C:\Users\elrog\COBRA\input files\new data\Output_080625\Outcome30.csv" --discountrate 2 
 
