"C:\Users\Loaner\COBRA\cobra_console.exe" -d "C:\Users\Loaner\COBRA\data\cobra.db" -b "C:\Users\Loaner\Desktop\powersystemspublichealth\BatchFileCreationCommands\Emissions_2023.csv" -c "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Emissions_Scenario_mixed_low_health_bound.csv" -p "C:\Users\Loaner\COBRA\input files\default data\default_2023_population_data.csv" -i "C:\Users\Loaner\COBRA\input files\default data\default_2023_incidence_data.csv" -v "C:\Users\Loaner\COBRA\input files\default data\default_2023_valuation_data.csv" -o "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Fall116mixlowGeneratorOutcome.csv" --discountrate 2 
 
"C:\Users\Loaner\COBRA\cobra_console.exe" -d "C:\Users\Loaner\COBRA\data\cobra.db" -b "C:\Users\Loaner\Desktop\powersystemspublichealth\BatchFileCreationCommands\Emissions_2023.csv" -c "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Emissions_Scenario_mixed_high_health_bound.csv" -p "C:\Users\Loaner\COBRA\input files\default data\default_2023_population_data.csv" -i "C:\Users\Loaner\COBRA\input files\default data\default_2023_incidence_data.csv" -v "C:\Users\Loaner\COBRA\input files\default data\default_2023_valuation_data.csv" -o "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Fall116mixhighGeneratorOutcome.csv" --discountrate 2 

"C:\Users\Loaner\COBRA\cobra_console.exe" -d "C:\Users\Loaner\COBRA\data\cobra.db" -b "C:\Users\Loaner\Desktop\powersystemspublichealth\BatchFileCreationCommands\Emissions_2023.csv" -c "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Emissions_Scenario_low_health_bound.csv" -p "C:\Users\Loaner\COBRA\input files\default data\default_2023_population_data.csv" -i "C:\Users\Loaner\COBRA\input files\default data\default_2023_incidence_data.csv" -v "C:\Users\Loaner\COBRA\input files\default data\default_2023_valuation_data.csv" -o "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Fall116lowhealthGeneratorOutcome.csv" --discountrate 2 

"C:\Users\Loaner\COBRA\cobra_console.exe" -d "C:\Users\Loaner\COBRA\data\cobra.db" -b "C:\Users\Loaner\Desktop\powersystemspublichealth\BatchFileCreationCommands\Emissions_2023.csv" -c "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Emissions_Scenario_high_health_bound.csv" -p "C:\Users\Loaner\COBRA\input files\default data\default_2023_population_data.csv" -i "C:\Users\Loaner\COBRA\input files\default data\default_2023_incidence_data.csv" -v "C:\Users\Loaner\COBRA\input files\default data\default_2023_valuation_data.csv" -o "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Fall116highhealthGeneratorOutcome.csv" --discountrate 2 

"C:\Users\Loaner\COBRA\cobra_console.exe" -d "C:\Users\Loaner\COBRA\data\cobra.db" -b "C:\Users\Loaner\Desktop\powersystemspublichealth\BatchFileCreationCommands\Emissions_2023.csv" -c "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Emissions_Scenario_carbon_emissions.csv" -p "C:\Users\Loaner\COBRA\input files\default data\default_2023_population_data.csv" -i "C:\Users\Loaner\COBRA\input files\default data\default_2023_incidence_data.csv" -v "C:\Users\Loaner\COBRA\input files\default data\default_2023_valuation_data.csv" -o "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Fall116CarbonEmissionsOutcome.csv" --discountrate 2 

"C:\Users\Loaner\COBRA\cobra_console.exe" -d "C:\Users\Loaner\COBRA\data\cobra.db" -b "C:\Users\Loaner\Desktop\powersystemspublichealth\BatchFileCreationCommands\Emissions_2023.csv" -c "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Emissions_Scenario_original_cost.csv" -p "C:\Users\Loaner\COBRA\input files\default data\default_2023_population_data.csv" -i "C:\Users\Loaner\COBRA\input files\default data\default_2023_incidence_data.csv" -v "C:\Users\Loaner\COBRA\input files\default data\default_2023_valuation_data.csv" -o "C:\Users\Loaner\Desktop\powersystemspublichealth\NewEnglandSpecificOutcomes\Fall116OriginalCostGeneratorOutcome.csv" --discountrate 2 

